### ISSUE TITLE
0.1.7 no longer compiles on stable Rust

### ISSUE THREAD

**Issue by 8573** [jedisct1/rust-clockpro-cache#5]
Version 0.1.6 of this crate worked with stable Rust, but version 0.1.7 no longer does, apparently because #2 added an unconditional dependency on the nightly-only `test` crate and the rustc feature of the same name.

I'd offer a patch to make the crate work on stable again, but nightly scares me and I don't know how to work with it….

**Comment by jedisct1** [comment]
The `test` crate can be replaced with `criterion`.

Do you think you could offer a PR that does that?
